apiVersion: v1
kind: Service
metadata:
  name: kill-my-cpu
  labels:
    app: kill-my-cpu
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: kill-my-cpu
